const Data=[
    {
        "id":1,
        "Address":"Forsmannstrabe5",
        "PostCode":22303,
        "PropertyType":"Flat",
        "Rooms":5,
        "Area":48
    },
    {
        "id":2,
        "Address":"Steinstrabe12",
        "PostCode":20095,
        "PropertyType":"TerracedHouse",
        "Rooms":7,
        "Area":63
    },
    {
        "id":3,
        "Address":"Himmelstrabe2",
        "PostCode":22299,
        "PropertyType":"Semidetached",
        "Rooms":3,
        "Area":22
    },
    {
        "id":4,
        "Address":"AlteSchieuse23",
        "PostCode":21107,
        "PropertyType":"TerracedHouse",
        "Rooms":4,
        "Area":54
    },
    {
        "id":5,
        "Address":"Islampura",
        "PostCode":54000,
        "PropertyType":"TerracedHouse",
        "Rooms":8,
        "Area":120
    },
    {
        "id":6,
        "Address":"Rajgarh",
        "PostCode":54123,
        "PropertyType":"Flat",
        "Rooms":5,
        "Area":540
    },
    {
        "id":7,
        "Address":"shamnagar",
        "PostCode":54521,
        "PropertyType":"TerracedHouse",
        "Rooms":4,
        "Area":54
    },
]
export default Data;